/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rolandsall.kafka.template.order.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8786516569988833609L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderAvroModel\",\"namespace\":\"com.rolandsall.kafka.template.order.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"trackingId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"orderStatus\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatus\",\"symbols\":[\"PENDING\",\"PAID\",\"APPROVED\",\"CANCELLING\",\"CANCELLED\"]}},{\"name\":\"orderItemList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderItem\",\"fields\":[{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"orderItemId\",\"type\":\"int\"},{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"price\",\"type\":\"long\"}]}}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<OrderAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String trackingId;
  private com.rolandsall.kafka.template.order.avro.model.OrderStatus orderStatus;
  private java.util.List<com.rolandsall.kafka.template.order.avro.model.OrderItem> orderItemList;
  private java.time.Instant createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param trackingId The new value for trackingId
   * @param orderStatus The new value for orderStatus
   * @param orderItemList The new value for orderItemList
   * @param createdAt The new value for createdAt
   */
  public OrderAvroModel(java.lang.String id, java.lang.String trackingId, com.rolandsall.kafka.template.order.avro.model.OrderStatus orderStatus, java.util.List<com.rolandsall.kafka.template.order.avro.model.OrderItem> orderItemList, java.time.Instant createdAt) {
    this.id = id;
    this.trackingId = trackingId;
    this.orderStatus = orderStatus;
    this.orderItemList = orderItemList;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return trackingId;
    case 2: return orderStatus;
    case 3: return orderItemList;
    case 4: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: trackingId = value$ != null ? value$.toString() : null; break;
    case 2: orderStatus = (com.rolandsall.kafka.template.order.avro.model.OrderStatus)value$; break;
    case 3: orderItemList = (java.util.List<com.rolandsall.kafka.template.order.avro.model.OrderItem>)value$; break;
    case 4: createdAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'trackingId' field.
   * @return The value of the 'trackingId' field.
   */
  public java.lang.String getTrackingId() {
    return trackingId;
  }


  /**
   * Sets the value of the 'trackingId' field.
   * @param value the value to set.
   */
  public void setTrackingId(java.lang.String value) {
    this.trackingId = value;
  }

  /**
   * Gets the value of the 'orderStatus' field.
   * @return The value of the 'orderStatus' field.
   */
  public com.rolandsall.kafka.template.order.avro.model.OrderStatus getOrderStatus() {
    return orderStatus;
  }


  /**
   * Sets the value of the 'orderStatus' field.
   * @param value the value to set.
   */
  public void setOrderStatus(com.rolandsall.kafka.template.order.avro.model.OrderStatus value) {
    this.orderStatus = value;
  }

  /**
   * Gets the value of the 'orderItemList' field.
   * @return The value of the 'orderItemList' field.
   */
  public java.util.List<com.rolandsall.kafka.template.order.avro.model.OrderItem> getOrderItemList() {
    return orderItemList;
  }


  /**
   * Sets the value of the 'orderItemList' field.
   * @param value the value to set.
   */
  public void setOrderItemList(java.util.List<com.rolandsall.kafka.template.order.avro.model.OrderItem> value) {
    this.orderItemList = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new OrderAvroModel RecordBuilder.
   * @return A new OrderAvroModel RecordBuilder
   */
  public static com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder newBuilder() {
    return new com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder();
  }

  /**
   * Creates a new OrderAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderAvroModel RecordBuilder
   */
  public static com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder newBuilder(com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder other) {
    if (other == null) {
      return new com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder();
    } else {
      return new com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new OrderAvroModel RecordBuilder by copying an existing OrderAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new OrderAvroModel RecordBuilder
   */
  public static com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder newBuilder(com.rolandsall.kafka.template.order.avro.model.OrderAvroModel other) {
    if (other == null) {
      return new com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder();
    } else {
      return new com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderAvroModel>
    implements org.apache.avro.data.RecordBuilder<OrderAvroModel> {

    private java.lang.String id;
    private java.lang.String trackingId;
    private com.rolandsall.kafka.template.order.avro.model.OrderStatus orderStatus;
    private java.util.List<com.rolandsall.kafka.template.order.avro.model.OrderItem> orderItemList;
    private java.time.Instant createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.trackingId)) {
        this.trackingId = data().deepCopy(fields()[1].schema(), other.trackingId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.orderStatus)) {
        this.orderStatus = data().deepCopy(fields()[2].schema(), other.orderStatus);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.orderItemList)) {
        this.orderItemList = data().deepCopy(fields()[3].schema(), other.orderItemList);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.rolandsall.kafka.template.order.avro.model.OrderAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.trackingId)) {
        this.trackingId = data().deepCopy(fields()[1].schema(), other.trackingId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderStatus)) {
        this.orderStatus = data().deepCopy(fields()[2].schema(), other.orderStatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.orderItemList)) {
        this.orderItemList = data().deepCopy(fields()[3].schema(), other.orderItemList);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'trackingId' field.
      * @return The value.
      */
    public java.lang.String getTrackingId() {
      return trackingId;
    }


    /**
      * Sets the value of the 'trackingId' field.
      * @param value The value of 'trackingId'.
      * @return This builder.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder setTrackingId(java.lang.String value) {
      validate(fields()[1], value);
      this.trackingId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'trackingId' field has been set.
      * @return True if the 'trackingId' field has been set, false otherwise.
      */
    public boolean hasTrackingId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'trackingId' field.
      * @return This builder.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder clearTrackingId() {
      trackingId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderStatus' field.
      * @return The value.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderStatus getOrderStatus() {
      return orderStatus;
    }


    /**
      * Sets the value of the 'orderStatus' field.
      * @param value The value of 'orderStatus'.
      * @return This builder.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder setOrderStatus(com.rolandsall.kafka.template.order.avro.model.OrderStatus value) {
      validate(fields()[2], value);
      this.orderStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orderStatus' field has been set.
      * @return True if the 'orderStatus' field has been set, false otherwise.
      */
    public boolean hasOrderStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orderStatus' field.
      * @return This builder.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder clearOrderStatus() {
      orderStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderItemList' field.
      * @return The value.
      */
    public java.util.List<com.rolandsall.kafka.template.order.avro.model.OrderItem> getOrderItemList() {
      return orderItemList;
    }


    /**
      * Sets the value of the 'orderItemList' field.
      * @param value The value of 'orderItemList'.
      * @return This builder.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder setOrderItemList(java.util.List<com.rolandsall.kafka.template.order.avro.model.OrderItem> value) {
      validate(fields()[3], value);
      this.orderItemList = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'orderItemList' field has been set.
      * @return True if the 'orderItemList' field has been set, false otherwise.
      */
    public boolean hasOrderItemList() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'orderItemList' field.
      * @return This builder.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder clearOrderItemList() {
      orderItemList = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[4], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.rolandsall.kafka.template.order.avro.model.OrderAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderAvroModel build() {
      try {
        OrderAvroModel record = new OrderAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.trackingId = fieldSetFlags()[1] ? this.trackingId : (java.lang.String) defaultValue(fields()[1]);
        record.orderStatus = fieldSetFlags()[2] ? this.orderStatus : (com.rolandsall.kafka.template.order.avro.model.OrderStatus) defaultValue(fields()[2]);
        record.orderItemList = fieldSetFlags()[3] ? this.orderItemList : (java.util.List<com.rolandsall.kafka.template.order.avro.model.OrderItem>) defaultValue(fields()[3]);
        record.createdAt = fieldSetFlags()[4] ? this.createdAt : (java.time.Instant) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<OrderAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










